version: '3.8'

services:
  frontend:
    build: .
    container_name: easygenerator-auth-frontend
    ports:
      - "3001:3000"
    environment:
      - BACKEND_URL=http://host.docker.internal:3000
      - NEXTAUTH_URL=http://localhost:3001
      - NEXTAUTH_SECRET=XZANATOL
      - PORT=3000
    restart: unless-stopped
    networks:
      - easygenerator-network

networks:
  easygenerator-network:
    driver: bridge