version: '3.8'

services:
  backend:
    container_name: easygenerator-auth-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "3000"
    environment:
      - environ=prod
      - PORT=3000
      - secretKey=${SECRET_KEY}
      - saltRounds=5
      - MONGO_URI=${MONGO_URI}
    restart: unless-stopped
    networks:
      - easygenerator-network

  frontend:
    container_name: easygenerator-auth-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - BACKEND_URL=${BACKEND_URL}
    expose:
      - "3000"
    environment:
      - BACKEND_URL=${BACKEND_URL}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${SECRET_KEY}
      - PUBLIC_URL=${FRONTEND_PUBLIC}
      - PORT=3000
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - easygenerator-network

networks:
  easygenerator-network:
    driver: bridge
